// Stub class generated by rmic - DO NOT EDIT!

public final class example_Counter_Stub
    extends java.rmi.server.RemoteStub
    implements Counter
{
    private static final long serialVersionUID = 2L;
    
    private static final long interfaceHash = 134793296L;
    
    private static boolean useNewInvoke;
    
    private static final java.rmi.server.Operation[] operations = {
        new java.rmi.server.Operation("int nextValue()")
    };
    
    private static java.lang.reflect.Method $method_nextValue_0;
    
    static {
        try {
            java.rmi.server.RemoteRef.class.getMethod("invoke", new java.lang.Class[] { java.rmi.Remote.class, java.lang.reflect.Method.class, java.lang.Object[].class, long.class });
            useNewInvoke = true;
            $method_nextValue_0 = example_Counter.class.getMethod("nextValue", new java.lang.Class[] {});
            
        }
        catch (java.lang.NoSuchMethodException e) {
            useNewInvoke = false;
        }
    }
    
    public example_Counter_Stub() {
        super();
    }
    public example_Counter_Stub(java.rmi.server.RemoteRef ref) {
        super(ref);
    }
